In [27]:
import numpy as np

In [28]:
grid_world = np.full((7,7),-1)
grid_world[0,0] = -101
grid_world[6,6] = 0
input_trap_value = [(0,2),(1,2),(3,4),(3,5),(6,2),(6,3)]
for i in input_trap_value:
    grid_world[i] = -100
print(grid_world)

[[-101   -1 -100   -1   -1   -1   -1]
 [  -1   -1 -100   -1   -1   -1   -1]
 [  -1   -1   -1   -1   -1   -1   -1]
 [  -1   -1   -1   -1 -100 -100   -1]
 [  -1   -1   -1   -1   -1   -1   -1]
 [  -1   -1   -1   -1   -1   -1   -1]
 [  -1   -1 -100 -100   -1   -1    0]]


In [29]:
action = ['Up', 'Down', 'Left', 'Right']

def get_state(position, action_idx):
    i, j = position
    if action_idx == 0:  # Up
        return max(0, i-1), j
    elif action_idx == 1:  # Down
        return min(6, i+1), j
    elif action_idx == 2:  # Left
        return i, max(0, j-1)
    elif action_idx == 3:  # Right
        return i, min(6, j+1)

def calculate_directions(value):
    direction_array = np.empty((7, 7), dtype='object')

    for i in range(7):
        for j in range(7):
            if i == 6 and j == 6:
                direction_array[i, j] = ['End']  # Terminal state
            else:
                compare_list = []
                for k in range(len(action)):
                    a, b = get_state([i, j], k)
                    compare_list.append(value[a][b])
                    
                max_indices = np.where(compare_list == np.max(compare_list))[0]
                max_directions = [action[idx] for idx in max_indices]
                direction_array[i, j] = max_directions
                
    return direction_array


In [21]:
# Policy Evaluation _ random policy

prev_state  = np.zeros((7,7))
next_state = np.zeros((7,7))
for k in range(1000):
    for i in range(grid_world.shape[0]):
        for j in range(grid_world.shape[1]):
            if i == 6 and j == 6:
                continue
            if i == 0: # up
                value_buf = 0.25*(grid_world[i,j] + prev_state[i,j])
            else:
                value_buf = 0.25*(grid_world[i,j] + prev_state[i-1,j])
            
            if i == 6: # down
                value_buf += 0.25*(grid_world[i,j] + prev_state[i,j])
            else:
                value_buf += 0.25*(grid_world[i,j] + prev_state[i+1,j])
            
            if j == 0: # left
                value_buf += 0.25*(grid_world[i,j] + prev_state[i,j])
            else:
                value_buf += 0.25*(grid_world[i,j] + prev_state[i,j-1])
            
            if j == 6: # right
                value_buf += 0.25*(grid_world[i,j] + prev_state[i,j])
            else:
                value_buf += 0.25*(grid_world[i,j] + prev_state[i,j+1])
            next_state[i,j] = value_buf
    print("k = {}".format(k))
    print(prev_state)
    prev_state = np.round(next_state, decimals=1)
print("k = 1000")
print(prev_state)

k = 0
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
k = 1
[[-101.   -1. -100.   -1.   -1.   -1.   -1.]
 [  -1.   -1. -100.   -1.   -1.   -1.   -1.]
 [  -1.   -1.   -1.   -1.   -1.   -1.   -1.]
 [  -1.   -1.   -1.   -1. -100. -100.   -1.]
 [  -1.   -1.   -1.   -1.   -1.   -1.   -1.]
 [  -1.   -1.   -1.   -1.   -1.   -1.   -1.]
 [  -1.   -1. -100. -100.   -1.   -1.    0.]]
k = 2
[[-152.   -51.8 -150.5  -26.8   -2.    -2.    -2. ]
 [ -27.   -26.8 -125.8  -26.8   -2.    -2.    -2. ]
 [  -2.    -2.   -26.8   -2.   -26.8  -26.8   -2. ]
 [  -2.    -2.    -2.   -26.8 -125.8 -125.8  -26.8]
 [  -2.    -2.    -2.    -2.   -26.8  -26.8   -2. ]
 [  -2.    -2.   -26.8  -26.8   -2.    -2.    -1.8]
 [  -2.   -26.8 -150.5 -150.5  -26.8   -1.8    0. ]]
k = 3
[[-196.7  -96.3 -188.7  -52.5   -9.2   -3.    -3. ]
 [ -53.   -52.6 -157.7  -40.2  -15.4   -9.2   -3. ]
 [  -9.2  -15.4  -34. 

In [30]:
# Policy Improvement _ random policy
result_directions = calculate_directions(prev_state)
print(result_directions)

[[list(['Down', 'Right']) list(['Down']) list(['Right'])
  list(['Down', 'Right']) list(['Down', 'Right']) list(['Down', 'Right'])
  list(['Down'])]
 [list(['Down', 'Right']) list(['Down']) list(['Down', 'Right'])
  list(['Down', 'Right']) list(['Down', 'Right']) list(['Down', 'Right'])
  list(['Down'])]
 [list(['Down', 'Right']) list(['Down', 'Right']) list(['Down', 'Right'])
  list(['Down', 'Right']) list(['Right']) list(['Right']) list(['Down'])]
 [list(['Down', 'Right']) list(['Down', 'Right']) list(['Down', 'Right'])
  list(['Down']) list(['Down']) list(['Down', 'Right']) list(['Down'])]
 [list(['Down', 'Right']) list(['Down', 'Right']) list(['Down', 'Right'])
  list(['Down', 'Right']) list(['Down', 'Right']) list(['Down', 'Right'])
  list(['Down'])]
 [list(['Right']) list(['Right']) list(['Right']) list(['Right'])
  list(['Down', 'Right']) list(['Down', 'Right']) list(['Down'])]
 [list(['Up', 'Right']) list(['Up']) list(['Up']) list(['Right'])
  list(['Right']) list(['Right']) li

In [31]:
# Policy Improvement _ greedy policy
prev_state  = np.zeros((7,7))
next_state = np.zeros((7,7))
for k in range(20):
    print("k = {}".format(k))
    print(prev_state)
    result_directions = calculate_directions(prev_state)
    print(result_directions)
    for i in range(grid_world.shape[0]):
        for j in range(grid_world.shape[1]):
            if i == 6 and j == 6:
                continue
            if k == 0:
                if i == 0: # up
                    value_buf = 0.25*(grid_world[i,j] + prev_state[i,j])
                else:
                    value_buf = 0.25*(grid_world[i,j] + prev_state[i-1,j])
                if i == 6: # down
                    value_buf += 0.25*(grid_world[i,j] + prev_state[i,j])
                else:
                    value_buf += 0.25*(grid_world[i,j] + prev_state[i+1,j])
                if j == 0: # left
                    value_buf += 0.25*(grid_world[i,j] + prev_state[i,j])
                else:
                    value_buf += 0.25*(grid_world[i,j] + prev_state[i,j-1])
                if j == 6: # right
                    value_buf += 0.25*(grid_world[i,j] + prev_state[i,j])
                else:
                    value_buf += 0.25*(grid_world[i,j] + prev_state[i,j+1])
                next_state[i,j] = value_buf
            else:
                if 'End' in result_directions[i,j]:
                    continue
                if len(result_directions[i,j]) == 0:
                    continue
                ratio = 1.0 / len(result_directions[i,j])
                value_buf = 0.0
                if 'Up' in result_directions[i,j]:
                    if i == 0: # up
                        value_buf += ratio*(grid_world[i,j] + prev_state[i,j])
                    else:
                        value_buf += ratio*(grid_world[i,j] + prev_state[i-1,j])
                        
                if 'Down' in result_directions[i,j]:
                    if i == 6: # down
                        value_buf += ratio*(grid_world[i,j] + prev_state[i,j])
                    else:
                        value_buf += ratio*(grid_world[i,j] + prev_state[i+1,j])

                if 'Left' in result_directions[i,j]:
                    if j == 0: # left
                        value_buf += ratio*(grid_world[i,j] + prev_state[i,j])
                    else:
                        value_buf += ratio*(grid_world[i,j] + prev_state[i,j-1])

                if 'Right' in result_directions[i,j]:
                    if j == 6: # right
                        value_buf += ratio*(grid_world[i,j] + prev_state[i,j])
                    else:
                        value_buf += ratio*(grid_world[i,j] + prev_state[i,j+1])
                    
                next_state[i,j] = value_buf
    prev_state = np.copy(next_state)
print("k = 20")
print(prev_state)
result_directions = calculate_directions(prev_state)
print(result_directions)

k = 0
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])]
 [list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])]
 [list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', 'Left', 'Right'])
  list(['Up', 'Down', '

In [33]:
#value Iteration
prev_state  = np.zeros((7,7))
next_state = np.zeros((7,7))
for k in range(15):
    print("k = {}".format(k))
    print(prev_state)
    for i in range(grid_world.shape[0]):
        for j in range(grid_world.shape[1]):
            if i == 6 and j == 6:
                continue
            if i == 0: # up
                value_buf = (grid_world[i,j] + prev_state[i,j])
            else:
                value_buf = (grid_world[i,j] + prev_state[i-1,j])
            
            if i == 6: # down
                if value_buf < (grid_world[i,j] + prev_state[i,j]):
                    value_buf = (grid_world[i,j] + prev_state[i,j])
            else:
                if value_buf < (grid_world[i,j] + prev_state[i+1,j]):
                    value_buf = (grid_world[i,j] + prev_state[i+1,j])
            
            if j == 0: # left
                if value_buf < (grid_world[i,j] + prev_state[i,j]):
                    value_buf = (grid_world[i,j] + prev_state[i,j])
            else:
                if value_buf < (grid_world[i,j] + prev_state[i,j-1]):
                    value_buf = (grid_world[i,j] + prev_state[i,j-1])
            
            if j == 6: # right
                if value_buf < (grid_world[i,j] + prev_state[i,j]):
                    value_buf = (grid_world[i,j] + prev_state[i,j])
            else:
                if value_buf < (grid_world[i,j] + prev_state[i,j+1]):
                    value_buf = (grid_world[i,j] + prev_state[i,j+1])
            next_state[i,j] = value_buf
    prev_state = np.copy(next_state)
print("k = 15")
print(prev_state)

k = 0
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
k = 1
[[-101.   -1. -100.   -1.   -1.   -1.   -1.]
 [  -1.   -1. -100.   -1.   -1.   -1.   -1.]
 [  -1.   -1.   -1.   -1.   -1.   -1.   -1.]
 [  -1.   -1.   -1.   -1. -100. -100.   -1.]
 [  -1.   -1.   -1.   -1.   -1.   -1.   -1.]
 [  -1.   -1.   -1.   -1.   -1.   -1.   -1.]
 [  -1.   -1. -100. -100.   -1.   -1.    0.]]
k = 2
[[-102.   -2. -101.   -2.   -2.   -2.   -2.]
 [  -2.   -2. -101.   -2.   -2.   -2.   -2.]
 [  -2.   -2.   -2.   -2.   -2.   -2.   -2.]
 [  -2.   -2.   -2.   -2. -101. -101.   -2.]
 [  -2.   -2.   -2.   -2.   -2.   -2.   -2.]
 [  -2.   -2.   -2.   -2.   -2.   -2.   -1.]
 [  -2.   -2. -101. -101.   -2.   -1.    0.]]
k = 3
[[-103.   -3. -102.   -3.   -3.   -3.   -3.]
 [  -3.   -3. -102.   -3.   -3.   -3.   -3.]
 [  -3.   -3.   -3.   -3.   -3.   -3.   -3.]
 [  -3.   -3.   -3.   -3. -102. -102.   